name: MAUM QA BUILD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: git clone & synchronize
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum2_HOST }}
        username: ${{ secrets.maum2_USERNAME }}
        password: ${{ secrets.maum2_PASSWORD }}
        port: ${{ secrets.maum2_PORT }}
        script: C:\node_deploy\script\git_clone.bat
        
    - name: node restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\batch2.bat
        
    - name: npm install
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\batch3.bat
                
    - name: npm install 2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\batch4.bat
                        
    - name: build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\batch5.bat
        
    - name: restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\batch6.bat
        
    - name: maumplus zip
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\zip_batch7.bat
        
    - name: maumplus zip sftp put
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\sftp_put_batch8.bat   
        
    - name: del zip
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.maum1_HOST }}
        username: ${{ secrets.maum1_USERNAME }}
        password: ${{ secrets.maum1_PASSWORD }}
        port: ${{ secrets.maum1_PORT }}
        script: C:\node_deploy\script\del_zip.batch9.bat
        
